language: rust
cache: cargo
sudo: false

rust:
  - stable
  - nightly

os:
  - linux

dist: xenial

before_script:
  - gcc -v
  - rustc -V
  - cargo -V

script:
  - cargo build --release --verbose
  - cargo test --release

addons:
  apt:
    packages:
      - gcc-6
      - g++-6