language: rust
sudo: false
cache:
  - directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

script:
  - cargo build --release --verbose

matrix:
  allow_failures:
     - rust: beta
     - rust: nightly