language: rust
cache: cargo
sudo: false

rust:
  - stable
  - nightly

os:
  - linux

dist: trusty

before_script:
  - gcc -v
  - rustc -V
  - cargo -V

script:
  - cargo build --release --verbose
  - cargo test --release