language: rust
sudo: false
cache:
  - directories:
    - $TRAVIS_BUILD_DIR/target
    - $HOME/.cargo

rust:
  - stable
  - nightly

os:
  - linux

dist: trusty

script:
  - cargo build --release --verbose
  